//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-test-kit open source project.
//
// Copyright (c) Margins Technologies LLC.
// Licensed under the Apache License, Version 2.0.
//
//===----------------------------------------------------------------------===//

/// Synthesizes partial ``Stateful`` conformance for enums.
///
/// Apply the `@Stateful` macro to an enum to automatically synthesize partial
/// ``Stateful`` conformance.
///
/// ```swift
/// @Stateful
/// enum CacheCommand
/// {
///     typealias System    = Cache<String, Int>
///     typealias Model     = Int
///
///     case insert(key: String, value: Int)
///     case lookup(key: String)
///     case delete(key: String)
///     case clear
///
///     // Generated by the macro automatically:
///     // - arbitrary(using:model:)
///     // - shrink()
///
///     // Must be added manually:
///     // - run(model:system:)
///     // - advance(model:)
///
///     // May be added manually:
///     // - precondition(model:)
///     // - postcondition(model:system:)
///     // - shrink(model:)
/// }
/// ```
///
/// Type aliases for the system and model are not required. If they are
/// omitted, the types of the system and model will be derived from the
/// signatures of the methods that must be manually added.
///
/// ## Command Generation
///
/// The generated method to create arbitrary values ignores the given `model`
/// parameter. Manually add the method to generate commands conditionally
/// based on the given model state, or use a precondition to filter invalid
/// commands after generation.
///
/// The default ``Stateful`` behavior is to select cases uniformly at random.
/// To control the frequency of individual cases, use the ``Weight(_:)`` macro.
/// Any case without an explicit weight defaults to a weight of `1`.
///
/// ```swift
/// @Stateful
/// enum CacheCommand
/// {
///     typealias System    = Cache<String, Int>
///     typealias Model     = Int
///
///     // insert is selected 5 times more often than delete or clear.
///     // lookup is selected 3 times more often than delete or clear.
///     @Weight(5) case insert(key: String, value: Int)
///     @Weight(3) case lookup(key: String)
///     @Weight(1) case delete(key: String)
///     case clear
/// }
/// ```
///
/// ## Shrinking
///
/// Shrinking follows the same strategy as the ``Arbitrary()`` macro.
///
/// ## Supported Enums
///
/// Conforming enums must have at least one case.
///
/// Recursive and `indirect` enums are supported, and follow the same strategy
/// as the ``Arbitrary()`` macro.
///
/// ## Generic Types
///
/// Generic parameters that appear in enum associated values are automatically
/// constrained to ``Arbitrary`` in the generated extension. Generic parameters
/// that are unused are not constrained.
///
/// ```swift
/// @Stateful
/// enum StoreCommand<T> where T : Sendable
/// {
///     typealias System    = ArrayStore<T>
///     typealias Model     = [T]
///
///     case reset
///     case append(T)
/// }
/// ```
@attached(
    extension,
    conformances:   Stateful,
    names:          named(arbitrary), named(shrink)
)
public macro Stateful() = #externalMacro(
    module:     "TestKitMacros",
    type:       "StatefulMacro"
)
