//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-test-kit open source project.
//
// Copyright (c) Margins Technologies LLC.
// Licensed under the Apache License, Version 2.0.
//
//===----------------------------------------------------------------------===//

extension Character: Arbitrary
{
    /// Generates an arbitrary value using the given generation context.
    /// - Parameter context: The generation context.
    /// - Returns: An arbitrary character, generated by delegating to
    /// ``Unicode/Scalar/arbitrary(using:)``.
    public static func arbitrary(
        using context: GenerationContext
    ) -> Character
    {
        return Character(Unicode.Scalar.arbitrary(using: context))
    }
    
    
    
    /// Generates candidate values that are smaller than the receiver value.
    ///
    /// Candidates converage toward `"a"`. Multi-scalar characters (grapheme
    /// clusters) shrink to `"a"` and the base scalar.
    ///
    /// - Returns: An array of smaller candidate values, or an empty array
    /// to indicate that no shrinking should occur.
    public func shrink() -> [Character]
    {
        /// `a` is used as the shrink target since it is readable and
        /// recognizable as the "lowest" character.
        let target = Character("a")
        
        guard self != target
        else
        {
            return []
        }
        
        
        
        let scalars: UnicodeScalarView = unicodeScalars
        
        /// Multi-scalars (grapheme clusters): try `a` and the base scalar.
        if scalars.count > 1
        {
            var candidates: [Character] = [target]
            
            if let first: Unicode.Scalar = scalars.first
            {
                let base = Character(first)
                
                if
                    base != self,
                    base != target
                {
                    candidates.append(base)
                }
            }
            
            return candidates
        }
        
        
        
        /// Single-scalars: search toward `a`.
        guard let scalar: Unicode.Scalar = scalars.first
        else
        {
            /// A valid `Character` should always have at least one scalar,
            /// so this should never happen.
            return [target]
        }
        
        return scalar.shrink().map { Character($0) }
    }
    
    
    
    /// Produces a value that is a small perturbation of the receiver value.
    /// - Parameter context: The generation context.
    /// - Returns: A mutated character.
    public func mutate(
        using context: GenerationContext
    ) -> Character
    {
        /// Multi-scalars (grapheme clusters) collapse to a single scalar
        /// after mutation, similar to shrinking. An alternative would be
        /// to preserve the cluster while mutating only a single scalar.
        
        guard let base: Unicode.Scalar = unicodeScalars.first
        else
        {
            return Character.arbitrary(using: context)
        }
        
        return Character(base.mutate(using: context))
    }
}
