//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-test-kit open source project.
//
// Copyright (c) Margins Technologies LLC.
// Licensed under the Apache License, Version 2.0.
//
//===----------------------------------------------------------------------===//

extension Substring: Arbitrary
{
    /// Generates an arbitrary value using the given generation context.
    /// - Parameter context: The generation context.
    /// - Returns: An arbitrary substring, generated by delegating to
    /// ``String/arbitrary(using:)``.
    public static func arbitrary(
        using context: GenerationContext
    ) -> Substring
    {
        return String.arbitrary(using: context)[...]
    }
    
    
    
    /// Generates candidate values that are smaller than the receiver value.
    ///
    /// Candidates are produced by converting to a string, shrinking the
    /// string, and converting back to a substring.
    ///
    /// - Returns: An array of smaller candidate values, or an empty array
    /// to indicate that no shrinking should occur.
    public func shrink() -> [Substring]
    {
        return String(self).shrink().map { $0[...] }
    }
    
    
    
    /// Produces a value that is a small perturbation of the receiver value.
    /// - Parameter context: The generation context.
    /// - Returns: A mutated substring.
    public func mutate(
        using context: GenerationContext
    ) -> Substring
    {
        return String(self).mutate(using: context)[...]
    }
}
